import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/header/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: '1 in 1 out App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <section id="screen" className='relative h-screen'>
          <Header />
          <main className="h-5/6 lg:px-16 lg:py-4">
            {children}
          </main>
        </section>
      </body>
    </html>
  )
}
